### ISSUE TITLE
Perform client health checks on start-up to further validate configuration

### ISSUE THREAD

**Issue by declark1** [foundation-model-stack/fms-guardrails-orchestrator#163]
## Description

As an extension of config validation, we should ensure that all clients (generation, detectors, chunkers) are healthy on start-up to catch any misconfigured endpoints or certs.

## Discussion

Currently, we create clients in `Orchestrator::new()` [here](https://github.com/foundation-model-stack/fms-guardrails-orchestrator/blob/main/src/orchestrator.rs#L60). Instead, we should create them after loading/validating the config [here](https://github.com/foundation-model-stack/fms-guardrails-orchestrator/blob/main/src/server.rs#L89), perform health checks, and inject them into `Orchestrator::new()` as a dependency.

We should panic in the event of a failed health check so that the configuration/other issue can be addressed.

The health checks can be triggered inside of `create_clients()` or as a separate function. To enable this functionality, `health` methods need to be implemented for each client. The gRPC clients (tgis, nlp, chunker) may not have the gRPC health service implemented (check and confirm). If not, let's discuss further offline as they may implement a separate standalone HTTP service for health checks.

## Acceptance Criteria

- [ ] Health methods are implemented for each client type
- [ ] Health checks are performed on start-up when clients are created
- [ ] Failed health checks panic with a descriptive error message indicating the specific client that is failing

**Comment by pscoro** [comment]
> but I’m concerned about the strategy of bringing down orchestrator on unhealthy/unready clients

Hey Evaline, in my PR I kept "run a health probe and aggregate the result" and "what do we do because of this result" as separate items. In theory you can run the probe whenever without it causing any effect on the orchestrators liveliness. The strategy of bringing down the orchestrator only happens during the "start up check" immediately after starting the orchestrator. If the readiness probe were to be triggered by a user visiting the endpoint this will have no effect on the orchestrator's liveliness. Similarly, if we are reading the results of the readiness probe at any other point in the orchestrator, we can choose whether failing health probe can imply fatal behaviour or not. At the moment it was just assumed that there needs to be a probe, exposed through an endpoint, and on start up if it fails the orchestrator is particularly likely to be misconfigured. maybe there can be a flag to bypass start up health checks (say we already know clients will fail, but we want to boot up the orchestrator anyway). Let me know what you think/if i misunderstood anything.

**Comment by pscoro** [comment]
Thanks, these are some good points.

To confirm, by "Orchestrator can be restarted for any normal reason listed above" you mean the orchestrator process is fully terminated and a new process is started correct? You're right that without additionally configuration if we tried to restart this orchestrator it would fail to start back up. From what Im seeing, having "start up readiness check" be toggleable would let us avoid this, unless theres something im missing. It looks to me like adding some additional configuration options may be a solution.

> Even if the behavior is not fatal, marking orchestrator itself overall un-ready by readiness probe due to one client also implies the same degree of cascading failure

I agree having more granularity to the orchestrator's overall readiness status would be nice, however im not certain where that distinction can be made. The readiness probe already returns a full list of health statuses for all clients, the overall status is just a summary based on "is there any non ready clients", its also up to the reader of the response to interpret what to do with this (ie the start up check reads this and interprets it as fatal)

Maybe instead of a more complicated "overall status", could it make more sense for the readiness probe to just return the list of client statuses and not make any overall claim about orchestrator readiness? Just an idea
